### ISSUE TITLE
error from Save Tox when saving new tox

### ISSUE THREAD

**Issue by radialbalance** [mir-lab/touchdesigner_ldi_projection_mapping_2019#2]
![Screen Shot 2019-11-12 at 1 20 07 PM](https://user-images.githubusercontent.com/10620456/68711785-34866680-054f-11ea-9ddf-25d656980f8c.jpg)

**Comment by radialbalance** [comment]
Marked tox in hot pink and made manual flder inside of TD-module

**Comment by radialbalance** [comment]
![Screen Shot 2019-11-12 at 1 23 20 PM](https://user-images.githubusercontent.com/10620456/68711972-9cd54800-054f-11ea-8d93-fb8f171a9199.jpg)

It appears that the file path has extra // in it, which isn't allowing the cmd+S to save project

**Comment by raganmd** [comment]
Change in the save tox - this uses the ctrl + w saving method, not the ctrl + s

ctrl + s should save the toe - this might be a Touch issue, not a save tox issue. Will continue to investigate.

**Comment by raganmd** [comment]
This was an icloud issue - in the future we should keep repos out of synced folders.
